name: Frankish Confederation CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BOT_TOKEN: 'MTA3OTUxNDI3MDYxNTc1MjgyNQ.GDSVLv.vgPgUleFEpeotnkdt4Jbw5uBXm3yg0iqynRsxQ'